version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
#    volumes:
#      - esdata:/usr/share/elasticsearch/data 

#volumes:
#  esdata:
#    driver: local